### ISSUE TITLE
Usage instructions 

### ISSUE THREAD

**Issue by firasm** [maracieco/md2canvas#9]
To run this code, here's what I did. Perhaps this could make its way into the readme if this is how the package is meant to be used?

## Usage

1. Grab your canvas course ID. 

For e.g., the course id is 45445 if the course URL is https://canvas.ubc.ca/courses/45445

2. Generate a new access token from Canvas

Login to Canvas, click "Account", click "Settings", scroll down and click "New Access Token"

3. Install the package 

`pip install git+https://github.com/maracieco/md2canvas`

4. Clone this repo locally

`git clone https://github.com/maracieco/md2canvas.git`

5. Change directory to the md2canvas folder

`cd md2canvas`

6. Install the requirements

`pip install -r requirements.txt`

7. Send a quiz to your canvas course

```
md2canvas -t <RedactedCanvasToken> -c 45445 -u https://canvas.ubc.ca ~/Sync/Teaching/utilities/md2canvas/examples/sample_quiz/SampleQuiz.md
```

--------

On another note, in the documentation, the file referenced is `simpleQuiz.md` but it should probably be:

`md2canvas ./examples/sample_quiz/SampleQuiz.md`

**Comment by maracieco** [comment]
Thank you, this is perfect. I will add it when I have time!

**Comment by maracieco** [comment]
@firasm I made a PR to add your instructions! #13
